OPENAI_API_KEY="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"

[postgres]
host = "localhost"
port = "5432"
database = "mlb_stats"
username = "minjong2237"
password = "1234"

[theme]
primaryColor = "#d33333" # MLB 느낌의 레드 포인트
backgroundColor = "#0E1117" # 딥 다크 배경
secondaryBackgroundColor = "#1E2329" # 사이드바/카드 배경
textColor = "#EAECEF" # 눈이 편한 화이트
font = "sans serif"